---
name: HTML-Latemp-GenMakeHelpers
version: 0.1.5
author:
  - Shlomi Fish <shlomif@iglu.org.il>
abstract: A Latemp Utility Module.
license: bsd
resources:
  license: http://www.opensource.org/licenses/bsd-license.php
requires:
  Class::Accessor: 0
  File::Basename: 0
  File::Find::Rule: 0
  Test::More: 0
provides:
  HTML::Latemp::GenMakeHelpers:
    file: lib/HTML/Latemp/GenMakeHelpers.pm
    version: 0.1.5
  HTML::Latemp::GenMakeHelpers::Base:
    file: lib/HTML/Latemp/GenMakeHelpers.pm
  HTML::Latemp::GenMakeHelpers::HostEntry:
    file: lib/HTML/Latemp/GenMakeHelpers.pm
generated_by: Module::Build version 0.2703
