---
name: HTML-Latemp-GenMakeHelpers
version: 0.2.0
author:
  - 'Shlomi Fish <shlomif@iglu.org.il>'
abstract: A Latemp Utility Module.
license: mit
resources:
  license: http://opensource.org/licenses/mit-license.php
requires:
  Class::Accessor: 0
  File::Basename: 0
  File::Find::Rule: 0
  base: 0
  strict: 0
  warnings: 0
build_requires:
  Test::More: 0
provides:
  HTML::Latemp::GenMakeHelpers:
    file: lib/HTML/Latemp/GenMakeHelpers.pm
    version: 0.2.0
  HTML::Latemp::GenMakeHelpers::Base:
    file: lib/HTML/Latemp/GenMakeHelpers.pm
  HTML::Latemp::GenMakeHelpers::Error:
    file: lib/HTML/Latemp/GenMakeHelpers.pm
  HTML::Latemp::GenMakeHelpers::Error::UncategorizedFile:
    file: lib/HTML/Latemp/GenMakeHelpers.pm
  HTML::Latemp::GenMakeHelpers::HostEntry:
    file: lib/HTML/Latemp/GenMakeHelpers.pm
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
